# This toolchain file was generated by Gradle to support NDK versions r14 and below.
include(/Users/gsthina/Library/Android/sdk/cmake/3.10.2.4988404/android.toolchain.cmake)
set(CMAKE_SYSTEM_VERSION 1)
