// Game = {}; 
// Game.scenes = []; 
// Game.scenes[1] = {}; 
// Game.layers = []; 
// Game.layers[1] = {}
var main_menu 			= [res.play_button, res.settings_button, res.credits_button, res.exit_button];
var sniper_points 		= [res.sniper_point];
var launch_position_x 	= 0;
var aliens 				= [res.alien_obj_1, res.alien_obj_2, res.alien_obj_3, res.alien_obj_4, res.alien_obj_5, res.alien_obj_6];
